pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/pratik-6958/testpratik.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    docker.image('maven:3.9.9-eclipse-temurin-17').inside(
                        '-v $HOME/.m2:/root/.m2'
                    ) {
                        sh 'mvn clean compile'
                    }
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh 'mvn sonar:sonar'
                }
            }
        }
    }
}
