apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 30s
    count: 3
    successCondition: result != nil && len(result) > 0 && result[0] >= 0.95
    failureCondition: result != nil && len(result) > 0 && result[0] < 0.90
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local
        query: |
          sum(rate(http_requests_total[1m]))
