apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 30 }
      - setWeight: 50
      - pause: { duration: 60 }
      - setWeight: 100
      analysis:
        templates:
        - templateName: success-rate
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: pratik6958/newapp:v.1
        ports:
        - containerPort: 80
